import "./_styles/globals.css";
import Header from "./_components/Header";
import NextThemesProvider from "./_components/theme-provider";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast"; // إضافة التوست

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: {
    template: "%s | Cyper",
    default: "Welcome | Cyper",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <NextThemesProvider>
          <header>
            <Header />
          </header>

          {children}

          <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
              success: {
                className: "bg-green-500 text-white",
                duration: 3000,
              },
              error: {
                className: "bg-red-500 text-white",
                duration: 3000,
              },
            }}
          />
        </NextThemesProvider>
      </body>
    </html>
  );
}
