import "./_styles/globals.css";
import Header from "./_components/Header";
import NextThemesProvider from "./_components/theme-provider";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: {
    template: "%s | Cyper",
    default: "Welcome | Cyper",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <NextThemesProvider>
          <Toaster position="top-right" />
          <header>
            <Header />
          </header>

          {children}
        </NextThemesProvider>
      </body>
    </html>
  );
}
